### PR TITLE
Update package.json to support next@14

### PR DESCRIPTION
**Pull request by noreiller**
Hi @josselinbuils, I hope you're going well. Here is a small PR to support next@14. :stuck_out_tongue:

### CODE REVIEW

**Comment by josselinbuils** [comment]
Hum, that's a lot of changes, not sure if I can handle this 🤔

**Review by josselinbuils — DISMISSED** [review]

**Comment by josselinbuils** [comment]
Like here: https://github.com/josselinbuils/next-bundle-analyzer/commit/573148d0dee32e0189c66f022b893463d848fa4c

**Comment by noreiller** [comment]
All done. :slightly_smiling_face:

**Review by josselinbuils — APPROVED** [review]

**Comment by josselinbuils** [comment]
Version published, thank you ❤️

**Comment by noreiller** [comment]
Thank you for your package :grinning:

**Pull request merged**
